name: CI

on: push

jobs:
  build:
    name: "build image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -f ./subproject2/Dockerfile -t my-app:latest .

      - name: Save Docker image as artifact
        run: docker save my-app:latest | gzip > my-app-latest.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-image
          path: my-app-latest.tar.gz

      
  test:
    name: "test image"
    runs-on: ubuntu-latest
    needs: build
    container:
      image: my-app:latest  # You specify the Docker image here
      options: --rm  # Clean up the container after execution
    steps:
      - name: Run
        run: uv run --package subproject2 pytest